### ISSUE TITLE
.NET Core 2.1 RC

### ISSUE THREAD

**Issue by christophwille** [dbarkol/azure-event-grid-viewer#1]
I had it published to Azure briefly during preview2 (your original code). Now with RC1 it is broken - looks like SignalR not pumping messages to the client because subscribe works, and EventGrid shows as delivered in its metrics. 

When I upgrade to RC1 Nuget (and publish), it gives me an internal error after deploying.

**Comment by dbarkol** [comment]
Looking into it, ran into the same issue last night.

**Comment by dbarkol** [comment]
Looks like some breaking changes to the RC1 release. You don't need to install the extensions and a few little things. Check this out in the meantime: https://github.com/dbarkol/EventGridViewer It has a deploy to Azure link too but you'll need to enable web sockets after manually (will fix that too).

**Comment by dbarkol** [comment]
Fixed. Will update blog post soon. Runtime is on Azure so no need to install extensions.
